services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl_certificate.pem:/etc/ssl/certs/ssl_certificate.pem;
      - ./ssl_certificate_key.pem:/etc/ssl/private/ssl_certificate_key.pem;

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
  
  postgres:
    image: postgres:17.5-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - relational-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      
  pgadmin:
    image: dpage/pgadmin4:9.6.0
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

  backend:
    build:
      context: .
      dockerfile: relational.Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  relational-db:
  pgadmin_data:
